### ISSUE TITLE
Git push clean repository

### ISSUE THREAD

**Issue by jmarceli** [goooseman/capistrano3-git-push#1]
Hey, this extension is a good idea, but it doesn't work when I have clean repository (everything is commited). It would be nice to always do the `git push` before deployment.

**Comment by goooseman** [comment]
@jmarceli Updated the gem. Please do `bundle update capistrano3-git-push` to update the gem.

**Comment by jmarceli** [comment]
Thanks. I'll check it with my next deploy.
